version: '3.8'
services:
  db:
    image: postgres:${POSTGRES_VERSION}
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./server/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    restart: always
    build:
      context: ./server
      dockerfile: ${DOCKERFILE}
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_PROTOCOL=${SERVER_PROTOCOL}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
    volumes:
      - ./server/config:/home/node/cokodocs/config
  client:
    restart: always
    build:
      context: ./client
      dockerfile: ${DOCKERFILE}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - CLIENT_PROTOCOL=${CLIENT_PROTOCOL}
      - CLIENT_HOST=${CLIENT_HOST}
      - CLIENT_PORT=${CLIENT_PORT}
    volumes:
      - ./app:/home/node/cokodocs/app
      - ./config:/home/node/cokodocs/config
